version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: research_excellence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    build: .
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=postgresql://postgres:${DB_PASSWORD}@db:5432/research_excellence
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMS_API_URL=${SMS_API_URL}
      - SMS_API_TOKEN=${SMS_API_TOKEN}
    ports:
      - "5500:5500"
    volumes:
      - app_uploads:/app/uploads
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  app_uploads: